SH = 'sh>'
URL = 'url>'
GIT = 'git>'
READFILE = 'read_file>'
K_SOURCE = 'source'
K_ON_START = 'on_start'
K_ACTIONS = 'actions'
K_LISTNER = 'listener'
K_DOC = 'doc'
LINE_BREAK = "\n"
SPACE = " "
CALLABLE = "callable"
PRE_DEFINED_KEYS = [K_SOURCE, K_ON_START, K_ACTIONS, K_LISTNER, K_DOC]
